// <auto-generated />
using CourierService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourierService.Migrations
{
    [DbContext(typeof(OfferCriteriaContext))]
    [Migration("20220803012643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27");

            modelBuilder.Entity("CourierService.Models.OfferCriteria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOfferActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDistance")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MinDistance")
                        .HasColumnType("REAL");

                    b.Property<double>("MinWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("OfferCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("OfferCriterias");
                });
#pragma warning restore 612, 618
        }
    }
}
